language: c
git:
   submodules: false
env:
  global:
    - LC_ALL=C
  matrix:
    - IMAGE=debian-amd64
      TARGET_LIST=x86_64-softmmu
    - IMAGE=debian-armel-cross
      TARGET_LIST=arm-softmmu
    - IMAGE=debian-armhf-cross
      TARGET_LIST=arm-softmmu
    - IMAGE=debian-arm64-cross
      TARGET_LIST=aarch64-softmmu
build:
  pre_ci:
    - make docker-image-${IMAGE} V=1
  pre_ci_boot:
    image_name: qemu
    image_tag: ${IMAGE}
    pull: false
    options: "-e HOME=/root"
  ci:
    - unset CC
    # some targets require newer up to date packages, for example TARGET_LIST matching
    # aarch64*-softmmu|arm*-softmmu)
    # see the configure script:
    #    error_exit "DTC (libfdt) version >= 1.4.2 not present. Your options:"
    #    "  (1) Preferred: Install the DTC (libfdt) devel package"
    #    "  (2) Fetch the DTC submodule, using:"
    #    "      git submodule update --init dtc"
    - dpkg --compare-versions `dpkg-query --showformat='${Version}' --show libfdt-dev` ge 1.4.2 || git submodule update --init dtc
    - ./configure ${QEMU_CONFIGURE_OPTS} --target-list=${TARGET_LIST}
    - make -j$(($(getconf _NPROCESSORS_ONLN) + 1))
